
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class NewJFrame extends javax.swing.JFrame {

    public ArrayList ballList = new ArrayList(100);
    public ArrayList buttonList = new ArrayList(100);
    public int[] intArray = massArray();
    public Ball tempBall;
    public boolean flag = false;
    public boolean isShrink = true;
    public boolean gameStart = false;
    public Grid movingGrid ;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt0 = new Grid(new Point(0,0));
        bt10 = new Grid(new Point(1,0));
        bt20 = new Grid(new Point(2,0));
        bt1 = new Grid(new Point(0,1));
        bt11 = new Grid(new Point(1,1));
        bt2 = new Grid(new Point(0,2));
        bt3 = new Grid(new Point(0,3));
        bt4 = new Grid(new Point(0,4));
        bt5 = new Grid(new Point(0,5));
        bt6 = new Grid(new Point(0,6));
        bt7 = new Grid(new Point(0,7));
        bt8 = new Grid(new Point(0,8));
        bt9 = new Grid(new Point(0,9));
        bt12 = new Grid(new Point(1,2));
        bt13 = new Grid(new Point(1,3));
        bt14 = new Grid(new Point(1,4));
        bt15 = new Grid(new Point(1,5));
        bt17 = new Grid(new Point(1,7));
        bt16 = new Grid(new Point(1,6));
        bt21 = new Grid(new Point(2,1));
        bt18 = new Grid(new Point(1,8));
        bt19 = new Grid(new Point(1,9));
        bt22 = new Grid(new Point(2,2));
        bt23 = new Grid(new Point(2,3));
        bt24 = new Grid(new Point(2,4));
        bt25 = new Grid(new Point(2,5));
        bt26 = new Grid(new Point(2,6));
        bt27 = new Grid(new Point(2,7));
        bt28 = new Grid(new Point(2,8));
        bt29 = new Grid(new Point(2,9));
        bt30 = new Grid(new Point(3,0));
        bt31 = new Grid(new Point(3,1));
        bt32 = new Grid(new Point(3,2));
        bt33 = new Grid(new Point(3,3));
        bt34 = new Grid(new Point(3,4));
        bt35 = new Grid(new Point(3,5));
        bt36 = new Grid(new Point(3,6));
        bt37 = new Grid(new Point(3,7));
        bt38 = new Grid(new Point(3,8));
        bt39 = new Grid(new Point(3,9));
        bt40 = new Grid(new Point(4,0));
        bt41 = new Grid(new Point(4,1));
        bt42 = new Grid(new Point(4,2));
        bt43 = new Grid(new Point(4,3));
        bt44 = new Grid(new Point(4,4));
        bt45 = new Grid(new Point(4,5));
        bt46 = new Grid(new Point(4,6));
        bt47 = new Grid(new Point(4,7));
        bt48 = new Grid(new Point(4,8));
        bt49 = new Grid(new Point(4,9));
        bt50 = new Grid(new Point(5,0));
        bt51 = new Grid(new Point(5,1));
        bt52 = new Grid(new Point(5,2));
        bt53 = new Grid(new Point(5,3));
        bt54 = new Grid(new Point(5,4));
        bt55 = new Grid(new Point(5,5));
        bt56 = new Grid(new Point(5,6));
        bt57 = new Grid(new Point(5,7));
        bt58 = new Grid(new Point(5,8));
        bt59 = new Grid(new Point(5,9));
        bt60 = new Grid(new Point(6,0));
        bt61 = new Grid(new Point(6,1));
        bt62 = new Grid(new Point(6,2));
        bt63 = new Grid(new Point(6,3));
        bt64 = new Grid(new Point(6,4));
        bt65 = new Grid(new Point(6,5));
        bt67 = new Grid(new Point(6,7));
        bt66 = new Grid(new Point(6,6));
        bt68 = new Grid(new Point(6,8));
        bt69 = new Grid(new Point(6,9));
        bt70 = new Grid(new Point(7,0));
        bt71 = new Grid(new Point(7,1));
        bt72 = new Grid(new Point(7,2));
        bt73 = new Grid(new Point(7,3));
        bt74 = new Grid(new Point(7,4));
        bt75 = new Grid(new Point(7,5));
        bt76 = new Grid(new Point(7,6));
        bt77 = new Grid(new Point(7,7));
        bt78 = new Grid(new Point(7,8));
        bt79 = new Grid(new Point(7,9));
        bt80 = new Grid(new Point(8,0));
        bt81 = new Grid(new Point(8,1));
        bt82 = new Grid(new Point(8,2));
        bt83 = new Grid(new Point(8,3));
        bt84 = new Grid(new Point(8,4));
        bt85 = new Grid(new Point(8,5));
        bt86 = new Grid(new Point(8,6));
        bt87 = new Grid(new Point(8,7));
        bt88 = new Grid(new Point(8,8));
        bt89 = new Grid(new Point(8,9));
        bt90 = new Grid(new Point(9,0));
        bt91 = new Grid(new Point(9,1));
        bt92 = new Grid(new Point(9,2));
        bt93 = new Grid(new Point(9,3));
        bt94 = new Grid(new Point(9,4));
        bt95 = new Grid(new Point(9,5));
        bt96 = new Grid(new Point(9,6));
        bt97 = new Grid(new Point(9,7));
        bt98 = new Grid(new Point(9,8));
        bt99 = new Grid(new Point(9,9));
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });

        jButton81.setText("游戏开始");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });

        jButton82.setText("难度选择");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });

        jButton83.setText("排行榜");

        jLabel1.setFont(new java.awt.Font("楷体", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("搞怪碰球");

        jLabel2.setFont(new java.awt.Font("楷体", 1, 24)); // NOI18N
        jLabel2.setText("得分：");

        jLabel3.setFont(new java.awt.Font("楷体", 1, 24)); // NOI18N
        jLabel3.setText("称号：");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton83, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton82, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        bt0.setPreferredSize(new java.awt.Dimension(40, 40));
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt0, gridBagConstraints);
        buttonList.add(bt0);
        buttonList.set(0, bt0);

        bt10.setPreferredSize(new java.awt.Dimension(40, 40));
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt10, gridBagConstraints);
        buttonList.add(bt10);

        bt20.setPreferredSize(new java.awt.Dimension(40, 40));
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt20, gridBagConstraints);
        buttonList.add(bt20);

        bt1.setPreferredSize(new java.awt.Dimension(40, 40));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt1, gridBagConstraints);
        buttonList.add(bt1);
        buttonList.set(1, bt1);

        bt11.setPreferredSize(new java.awt.Dimension(40, 40));
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt11, gridBagConstraints);
        buttonList.add(bt11);

        bt2.setPreferredSize(new java.awt.Dimension(40, 40));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt2, gridBagConstraints);
        buttonList.add(bt2);
        buttonList.set(2, bt2);

        bt3.setPreferredSize(new java.awt.Dimension(40, 40));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt3, gridBagConstraints);
        buttonList.add(bt3);
        buttonList.set(3, bt3);

        bt4.setPreferredSize(new java.awt.Dimension(40, 40));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt4, gridBagConstraints);
        buttonList.add(bt4);
        buttonList.set(4, bt4);

        bt5.setPreferredSize(new java.awt.Dimension(40, 40));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt5, gridBagConstraints);
        buttonList.add(bt5);
        buttonList.set(5, bt5);

        bt6.setPreferredSize(new java.awt.Dimension(40, 40));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt6, gridBagConstraints);
        buttonList.add(bt6);
        buttonList.set(6, bt6);

        bt7.setPreferredSize(new java.awt.Dimension(40, 40));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt7, gridBagConstraints);
        buttonList.add(bt7);
        buttonList.set(7, bt7);

        bt8.setPreferredSize(new java.awt.Dimension(40, 40));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt8, gridBagConstraints);
        buttonList.add(bt8);
        buttonList.set(8, bt8);

        bt9.setPreferredSize(new java.awt.Dimension(40, 40));
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        jPanel1.add(bt9, gridBagConstraints);
        buttonList.add(bt9);
        buttonList.set(9, bt9);

        bt12.setPreferredSize(new java.awt.Dimension(40, 40));
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt12, gridBagConstraints);
        buttonList.add(bt12);

        bt13.setPreferredSize(new java.awt.Dimension(40, 40));
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt13, gridBagConstraints);
        buttonList.add(bt13);

        bt14.setPreferredSize(new java.awt.Dimension(40, 40));
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt14, gridBagConstraints);
        buttonList.add(bt14);

        bt15.setPreferredSize(new java.awt.Dimension(40, 40));
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt15, gridBagConstraints);
        buttonList.add(bt15);

        bt17.setPreferredSize(new java.awt.Dimension(40, 40));
        bt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt17ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt17, gridBagConstraints);
        buttonList.add(bt17);

        bt16.setPreferredSize(new java.awt.Dimension(40, 40));
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt16, gridBagConstraints);
        buttonList.add(bt16);

        bt21.setPreferredSize(new java.awt.Dimension(40, 40));
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt21ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt21, gridBagConstraints);
        buttonList.add(bt21);

        bt18.setPreferredSize(new java.awt.Dimension(40, 40));
        bt18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt18ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt18, gridBagConstraints);
        buttonList.add(bt18);

        bt19.setPreferredSize(new java.awt.Dimension(40, 40));
        bt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt19ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt19, gridBagConstraints);
        buttonList.add(bt19);

        bt22.setPreferredSize(new java.awt.Dimension(40, 40));
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt22ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt22, gridBagConstraints);
        buttonList.add(bt22);

        bt23.setPreferredSize(new java.awt.Dimension(40, 40));
        bt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt23ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt23, gridBagConstraints);
        buttonList.add(bt23);

        bt24.setPreferredSize(new java.awt.Dimension(40, 40));
        bt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt24ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt24, gridBagConstraints);
        buttonList.add(bt24);

        bt25.setPreferredSize(new java.awt.Dimension(40, 40));
        bt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt25ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt25, gridBagConstraints);
        buttonList.add(bt25);

        bt26.setPreferredSize(new java.awt.Dimension(40, 40));
        bt26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt26ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt26, gridBagConstraints);
        buttonList.add(bt26);

        bt27.setPreferredSize(new java.awt.Dimension(40, 40));
        bt27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt27ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt27, gridBagConstraints);
        buttonList.add(bt27);

        bt28.setPreferredSize(new java.awt.Dimension(40, 40));
        bt28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt28ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt28, gridBagConstraints);
        buttonList.add(bt28);

        bt29.setPreferredSize(new java.awt.Dimension(40, 40));
        bt29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt29ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        jPanel1.add(bt29, gridBagConstraints);
        buttonList.add(bt29);

        bt30.setPreferredSize(new java.awt.Dimension(40, 40));
        bt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt30ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt30, gridBagConstraints);
        buttonList.add(bt30);

        bt31.setPreferredSize(new java.awt.Dimension(40, 40));
        bt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt31ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt31, gridBagConstraints);
        buttonList.add(bt31);

        bt32.setPreferredSize(new java.awt.Dimension(40, 40));
        bt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt32ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt32, gridBagConstraints);
        buttonList.add(bt32);

        bt33.setPreferredSize(new java.awt.Dimension(40, 40));
        bt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt33ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt33, gridBagConstraints);
        buttonList.add(bt33);

        bt34.setPreferredSize(new java.awt.Dimension(40, 40));
        bt34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt34ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt34, gridBagConstraints);
        buttonList.add(bt34);

        bt35.setPreferredSize(new java.awt.Dimension(40, 40));
        bt35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt35ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt35, gridBagConstraints);
        buttonList.add(bt35);

        bt36.setPreferredSize(new java.awt.Dimension(40, 40));
        bt36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt36ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt36, gridBagConstraints);
        buttonList.add(bt36);

        bt37.setPreferredSize(new java.awt.Dimension(40, 40));
        bt37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt37ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt37, gridBagConstraints);
        buttonList.add(bt37);

        bt38.setPreferredSize(new java.awt.Dimension(40, 40));
        bt38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt38ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt38, gridBagConstraints);
        buttonList.add(bt38);

        bt39.setPreferredSize(new java.awt.Dimension(40, 40));
        bt39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt39ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        jPanel1.add(bt39, gridBagConstraints);
        buttonList.add(bt39);

        bt40.setPreferredSize(new java.awt.Dimension(40, 40));
        bt40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt40ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt40, gridBagConstraints);
        buttonList.add(bt40);

        bt41.setPreferredSize(new java.awt.Dimension(40, 40));
        bt41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt41ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt41, gridBagConstraints);
        buttonList.add(bt41);

        bt42.setPreferredSize(new java.awt.Dimension(40, 40));
        bt42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt42ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt42, gridBagConstraints);
        buttonList.add(bt42);

        bt43.setPreferredSize(new java.awt.Dimension(40, 40));
        bt43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt43, gridBagConstraints);
        buttonList.add(bt43);

        bt44.setPreferredSize(new java.awt.Dimension(40, 40));
        bt44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt44ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt44, gridBagConstraints);
        buttonList.add(bt44);

        bt45.setPreferredSize(new java.awt.Dimension(40, 40));
        bt45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt45ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt45, gridBagConstraints);
        buttonList.add(bt45);

        bt46.setPreferredSize(new java.awt.Dimension(40, 40));
        bt46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt46ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt46, gridBagConstraints);
        buttonList.add(bt46);

        bt47.setPreferredSize(new java.awt.Dimension(40, 40));
        bt47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt47ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt47, gridBagConstraints);
        buttonList.add(bt47);

        bt48.setPreferredSize(new java.awt.Dimension(40, 40));
        bt48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt48ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt48, gridBagConstraints);
        buttonList.add(bt48);

        bt49.setPreferredSize(new java.awt.Dimension(40, 40));
        bt49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt49ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        jPanel1.add(bt49, gridBagConstraints);
        buttonList.add(bt49);

        bt50.setPreferredSize(new java.awt.Dimension(40, 40));
        bt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt50ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt50, gridBagConstraints);
        buttonList.add(bt50);

        bt51.setPreferredSize(new java.awt.Dimension(40, 40));
        bt51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt51ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt51, gridBagConstraints);
        buttonList.add(bt51);

        bt52.setPreferredSize(new java.awt.Dimension(40, 40));
        bt52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt52ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt52, gridBagConstraints);
        buttonList.add(bt52);

        bt53.setPreferredSize(new java.awt.Dimension(40, 40));
        bt53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt53ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt53, gridBagConstraints);
        buttonList.add(bt53);

        bt54.setPreferredSize(new java.awt.Dimension(40, 40));
        bt54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt54ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt54, gridBagConstraints);
        buttonList.add(bt54);

        bt55.setPreferredSize(new java.awt.Dimension(40, 40));
        bt55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt55ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt55, gridBagConstraints);
        buttonList.add(bt55);

        bt56.setPreferredSize(new java.awt.Dimension(40, 40));
        bt56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt56ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt56, gridBagConstraints);
        buttonList.add(bt56);

        bt57.setPreferredSize(new java.awt.Dimension(40, 40));
        bt57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt57ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt57, gridBagConstraints);
        buttonList.add(bt57);

        bt58.setPreferredSize(new java.awt.Dimension(40, 40));
        bt58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt58ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt58, gridBagConstraints);
        buttonList.add(bt58);

        bt59.setPreferredSize(new java.awt.Dimension(40, 40));
        bt59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt59ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        jPanel1.add(bt59, gridBagConstraints);
        buttonList.add(bt59);

        bt60.setPreferredSize(new java.awt.Dimension(40, 40));
        bt60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt60ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt60, gridBagConstraints);
        buttonList.add(bt60);

        bt61.setPreferredSize(new java.awt.Dimension(40, 40));
        bt61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt61ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt61, gridBagConstraints);
        buttonList.add(bt61);

        bt62.setPreferredSize(new java.awt.Dimension(40, 40));
        bt62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt62ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt62, gridBagConstraints);
        buttonList.add(bt62);

        bt63.setPreferredSize(new java.awt.Dimension(40, 40));
        bt63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt63ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt63, gridBagConstraints);
        buttonList.add(bt63);

        bt64.setPreferredSize(new java.awt.Dimension(40, 40));
        bt64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt64ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt64, gridBagConstraints);
        buttonList.add(bt64);

        bt65.setPreferredSize(new java.awt.Dimension(40, 40));
        bt65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt65ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt65, gridBagConstraints);
        buttonList.add(bt65);

        bt67.setPreferredSize(new java.awt.Dimension(40, 40));
        bt67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt67ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt67, gridBagConstraints);
        buttonList.add(bt67);

        bt66.setPreferredSize(new java.awt.Dimension(40, 40));
        bt66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt66ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt66, gridBagConstraints);
        buttonList.add(bt66);

        bt68.setPreferredSize(new java.awt.Dimension(40, 40));
        bt68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt68ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt68, gridBagConstraints);
        buttonList.add(bt68);

        bt69.setPreferredSize(new java.awt.Dimension(40, 40));
        bt69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt69ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        jPanel1.add(bt69, gridBagConstraints);
        buttonList.add(bt69);

        bt70.setPreferredSize(new java.awt.Dimension(40, 40));
        bt70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt70ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt70, gridBagConstraints);
        buttonList.add(bt70);

        bt71.setPreferredSize(new java.awt.Dimension(40, 40));
        bt71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt71ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt71, gridBagConstraints);
        buttonList.add(bt71);

        bt72.setPreferredSize(new java.awt.Dimension(40, 40));
        bt72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt72ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt72, gridBagConstraints);
        buttonList.add(bt72);

        bt73.setPreferredSize(new java.awt.Dimension(40, 40));
        bt73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt73ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt73, gridBagConstraints);
        buttonList.add(bt73);

        bt74.setPreferredSize(new java.awt.Dimension(40, 40));
        bt74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt74ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt74, gridBagConstraints);
        buttonList.add(bt74);

        bt75.setPreferredSize(new java.awt.Dimension(40, 40));
        bt75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt75ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt75, gridBagConstraints);
        buttonList.add(bt75);

        bt76.setPreferredSize(new java.awt.Dimension(40, 40));
        bt76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt76ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt76, gridBagConstraints);
        buttonList.add(bt76);

        bt77.setPreferredSize(new java.awt.Dimension(40, 40));
        bt77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt77ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt77, gridBagConstraints);
        buttonList.add(bt77);

        bt78.setPreferredSize(new java.awt.Dimension(40, 40));
        bt78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt78ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt78, gridBagConstraints);
        buttonList.add(bt78);

        bt79.setPreferredSize(new java.awt.Dimension(40, 40));
        bt79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt79ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        jPanel1.add(bt79, gridBagConstraints);
        buttonList.add(bt79);

        bt80.setPreferredSize(new java.awt.Dimension(40, 40));
        bt80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt80ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt80, gridBagConstraints);
        buttonList.add(bt80);

        bt81.setPreferredSize(new java.awt.Dimension(40, 40));
        bt81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt81ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt81, gridBagConstraints);
        buttonList.add(bt81);

        bt82.setPreferredSize(new java.awt.Dimension(40, 40));
        bt82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt82ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt82, gridBagConstraints);
        buttonList.add(bt82);

        bt83.setPreferredSize(new java.awt.Dimension(40, 40));
        bt83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt83ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt83, gridBagConstraints);
        buttonList.add(bt83);

        bt84.setPreferredSize(new java.awt.Dimension(40, 40));
        bt84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt84ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt84, gridBagConstraints);
        buttonList.add(bt84);

        bt85.setPreferredSize(new java.awt.Dimension(40, 40));
        bt85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt85ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt85, gridBagConstraints);
        buttonList.add(bt85);

        bt86.setPreferredSize(new java.awt.Dimension(40, 40));
        bt86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt86ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt86, gridBagConstraints);
        buttonList.add(bt86);

        bt87.setPreferredSize(new java.awt.Dimension(40, 40));
        bt87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt87ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt87, gridBagConstraints);
        buttonList.add(bt87);

        bt88.setPreferredSize(new java.awt.Dimension(40, 40));
        bt88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt88ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt88, gridBagConstraints);
        buttonList.add(bt88);

        bt89.setPreferredSize(new java.awt.Dimension(40, 40));
        bt89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt89ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        jPanel1.add(bt89, gridBagConstraints);
        buttonList.add(bt89);

        bt90.setPreferredSize(new java.awt.Dimension(40, 40));
        bt90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt90ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt90, gridBagConstraints);
        buttonList.add(bt90);

        bt91.setPreferredSize(new java.awt.Dimension(40, 40));
        bt91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt91ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt91, gridBagConstraints);
        buttonList.add(bt91);

        bt92.setPreferredSize(new java.awt.Dimension(40, 40));
        bt92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt92ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt92, gridBagConstraints);
        buttonList.add(bt92);

        bt93.setPreferredSize(new java.awt.Dimension(40, 40));
        bt93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt93ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt93, gridBagConstraints);
        buttonList.add(bt93);

        bt94.setPreferredSize(new java.awt.Dimension(40, 40));
        bt94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt94ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt94, gridBagConstraints);
        buttonList.add(bt94);

        bt95.setPreferredSize(new java.awt.Dimension(40, 40));
        bt95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt95ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt95, gridBagConstraints);
        buttonList.add(bt95);

        bt96.setPreferredSize(new java.awt.Dimension(40, 40));
        bt96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt96ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt96, gridBagConstraints);
        buttonList.add(bt96);

        bt97.setPreferredSize(new java.awt.Dimension(40, 40));
        bt97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt97ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt97, gridBagConstraints);
        buttonList.add(bt97);

        bt98.setPreferredSize(new java.awt.Dimension(40, 40));
        bt98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt98ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt98, gridBagConstraints);
        buttonList.add(bt98);

        bt99.setPreferredSize(new java.awt.Dimension(40, 40));
        bt99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt99ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        jPanel1.add(bt99, gridBagConstraints);
        buttonList.add(bt99);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("文件");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("编辑");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton80ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        buttonAction(0);
    }//GEN-LAST:event_bt0ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        if(!gameStart){
            createThreeBall();
            gameStart = true;
        }
    }//GEN-LAST:event_jButton81ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        buttonAction(1);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        
        buttonAction(9);
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
                buttonAction(2);     // TODO add your handling code here:
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        
        buttonAction(3);       // TODO add your handling code here:
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        
        buttonAction(4);     // TODO add your handling code here:
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        
        buttonAction(5);     // TODO add your handling code here:
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        
        buttonAction(6);      // TODO add your handling code here:
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        
        buttonAction(7);       // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        
        buttonAction(8);     // TODO add your handling code here:
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        buttonList.set(10, bt10);
        buttonAction(10);       // TODO add your handling code here:
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        buttonList.set(11, bt11);
        buttonAction(11);        // TODO add your handling code here:
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        buttonList.set(12, bt12);
        buttonAction(12);       // TODO add your handling code here:
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
        buttonList.set(13, bt13);
        buttonAction(13);     // TODO add your handling code here:
    }//GEN-LAST:event_bt13ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
        buttonList.set(14, bt14);
        buttonAction(14);       // TODO add your handling code here:
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
        buttonList.set(15, bt15);
        buttonAction(15);     // TODO add your handling code here:
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
        buttonList.set(16, bt16);
        buttonAction(16);       // TODO add your handling code here:
    }//GEN-LAST:event_bt16ActionPerformed

    private void bt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt17ActionPerformed
        buttonList.set(17, bt17);
        buttonAction(17);    // TODO add your handling code here:
    }//GEN-LAST:event_bt17ActionPerformed

    private void bt18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt18ActionPerformed
        buttonList.set(18, bt18);
        buttonAction(18);        // TODO add your handling code here:
    }//GEN-LAST:event_bt18ActionPerformed

    private void bt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt19ActionPerformed
        buttonList.set(19, bt19);
        buttonAction(19);        // TODO add your handling code here:
    }//GEN-LAST:event_bt19ActionPerformed

    private void bt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt20ActionPerformed
        buttonList.set(20, bt20);
        buttonAction(20);        // TODO add your handling code here:
    }//GEN-LAST:event_bt20ActionPerformed

    private void bt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt21ActionPerformed
        buttonList.set(21, bt21);
        buttonAction(21);        // TODO add your handling code here:
    }//GEN-LAST:event_bt21ActionPerformed

    private void bt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt22ActionPerformed
        buttonList.set(22, bt22);
        buttonAction(22);        // TODO add your handling code here:
    }//GEN-LAST:event_bt22ActionPerformed

    private void bt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt23ActionPerformed
        buttonList.set(23, bt23);
        buttonAction(23);       // TODO add your handling code here:
    }//GEN-LAST:event_bt23ActionPerformed

    private void bt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt24ActionPerformed
        buttonList.set(24, bt24);
        buttonAction(24);        // TODO add your handling code here:
    }//GEN-LAST:event_bt24ActionPerformed

    private void bt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt25ActionPerformed
        buttonList.set(25, bt25);
        buttonAction(25);      // TODO add your handling code here:
    }//GEN-LAST:event_bt25ActionPerformed

    private void bt26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt26ActionPerformed
        buttonList.set(26, bt26);
        buttonAction(26);       // TODO add your handling code here:
    }//GEN-LAST:event_bt26ActionPerformed

    private void bt27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt27ActionPerformed
        buttonList.set(27, bt27);
        buttonAction(27);        // TODO add your handling code here:
    }//GEN-LAST:event_bt27ActionPerformed

    private void bt28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt28ActionPerformed
        buttonList.set(28, bt28);
        buttonAction(28);       // TODO add your handling code here:
    }//GEN-LAST:event_bt28ActionPerformed

    private void bt29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt29ActionPerformed
        buttonList.set(29, bt29);
        buttonAction(29);        // TODO add your handling code here:
    }//GEN-LAST:event_bt29ActionPerformed

    private void bt30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt30ActionPerformed
        buttonList.set(30, bt30);
        buttonAction(30);       // TODO add your handling code here:
    }//GEN-LAST:event_bt30ActionPerformed

    private void bt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt31ActionPerformed
        buttonList.set(31, bt31);
        buttonAction(31);     // TODO add your handling code here:
    }//GEN-LAST:event_bt31ActionPerformed

    private void bt32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt32ActionPerformed
        buttonList.set(32, bt32);
        buttonAction(32);     // TODO add your handling code here:
    }//GEN-LAST:event_bt32ActionPerformed

    private void bt33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt33ActionPerformed
        buttonList.set(33, bt33);
        buttonAction(33);      // TODO add your handling code here:
    }//GEN-LAST:event_bt33ActionPerformed

    private void bt34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt34ActionPerformed
        buttonList.set(34, bt34);
        buttonAction(34);       // TODO add your handling code here:
    }//GEN-LAST:event_bt34ActionPerformed

    private void bt35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt35ActionPerformed
        buttonList.set(35, bt35);
        buttonAction(35);        // TODO add your handling code here:
    }//GEN-LAST:event_bt35ActionPerformed

    private void bt36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt36ActionPerformed
        buttonList.set(36, bt36);
        buttonAction(36);      // TODO add your handling code here:
    }//GEN-LAST:event_bt36ActionPerformed

    private void bt37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt37ActionPerformed
        buttonList.set(37, bt37);
        buttonAction(37);      // TODO add your handling code here:
    }//GEN-LAST:event_bt37ActionPerformed

    private void bt38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt38ActionPerformed
        buttonList.set(38, bt38);
        buttonAction(38);       // TODO add your handling code here:
    }//GEN-LAST:event_bt38ActionPerformed

    private void bt39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt39ActionPerformed
        buttonList.set(39, bt39);
        buttonAction(39);     // TODO add your handling code here:
    }//GEN-LAST:event_bt39ActionPerformed

    private void bt40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt40ActionPerformed
        buttonList.set(40, bt40);
        buttonAction(40);     // TODO add your handling code here:
    }//GEN-LAST:event_bt40ActionPerformed

    private void bt41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt41ActionPerformed
        buttonList.set(41, bt41);
        buttonAction(41);       // TODO add your handling code here:
    }//GEN-LAST:event_bt41ActionPerformed

    private void bt42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt42ActionPerformed
        buttonList.set(42, bt42);
        buttonAction(42);       // TODO add your handling code here:
    }//GEN-LAST:event_bt42ActionPerformed

    private void bt43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt43ActionPerformed
        buttonList.set(43, bt43);
        buttonAction(43);     // TODO add your handling code here:
    }//GEN-LAST:event_bt43ActionPerformed

    private void bt44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt44ActionPerformed
        buttonList.set(44, bt44);
        buttonAction(44);     // TODO add your handling code here:
    }//GEN-LAST:event_bt44ActionPerformed

    private void bt45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt45ActionPerformed
        buttonList.set(45, bt45);
        buttonAction(45);       // TODO add your handling code here:
    }//GEN-LAST:event_bt45ActionPerformed

    private void bt46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt46ActionPerformed
        buttonList.set(46, bt46);
        buttonAction(46);        // TODO add your handling code here:
    }//GEN-LAST:event_bt46ActionPerformed

    private void bt47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt47ActionPerformed
        buttonList.set(47, bt47);
        buttonAction(47);        // TODO add your handling code here:
    }//GEN-LAST:event_bt47ActionPerformed

    private void bt48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt48ActionPerformed
        buttonList.set(48, bt48);
        buttonAction(48);        // TODO add your handling code here:
    }//GEN-LAST:event_bt48ActionPerformed

    private void bt49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt49ActionPerformed
        buttonList.set(49, bt49);
        buttonAction(49);      // TODO add your handling code here:
    }//GEN-LAST:event_bt49ActionPerformed

    private void bt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt50ActionPerformed
        buttonList.set(50, bt50);
        buttonAction(50);      // TODO add your handling code here:
    }//GEN-LAST:event_bt50ActionPerformed

    private void bt51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt51ActionPerformed
        buttonList.set(51, bt51);
        buttonAction(51);      // TODO add your handling code here:
    }//GEN-LAST:event_bt51ActionPerformed

    private void bt52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt52ActionPerformed
        buttonList.set(52, bt52);
        buttonAction(52);        // TODO add your handling code here:
    }//GEN-LAST:event_bt52ActionPerformed

    private void bt53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt53ActionPerformed
        buttonList.set(53, bt53);
        buttonAction(53);      // TODO add your handling code here:
    }//GEN-LAST:event_bt53ActionPerformed

    private void bt54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt54ActionPerformed
        buttonList.set(54, bt54);
        buttonAction(54);     // TODO add your handling code here:
    }//GEN-LAST:event_bt54ActionPerformed

    private void bt55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt55ActionPerformed
        buttonList.set(55, bt55);
        buttonAction(55);        // TODO add your handling code here:
    }//GEN-LAST:event_bt55ActionPerformed

    private void bt56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt56ActionPerformed
        buttonList.set(56, bt56);
        buttonAction(56);        // TODO add your handling code here:
    }//GEN-LAST:event_bt56ActionPerformed

    private void bt57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt57ActionPerformed
        buttonList.set(57, bt57);
        buttonAction(57);       // TODO add your handling code here:
    }//GEN-LAST:event_bt57ActionPerformed

    private void bt58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt58ActionPerformed
        buttonList.set(58, bt58);
        buttonAction(58);        // TODO add your handling code here:
    }//GEN-LAST:event_bt58ActionPerformed

    private void bt59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt59ActionPerformed
        buttonList.set(49, bt59);
        buttonAction(59);       // TODO add your handling code here:
    }//GEN-LAST:event_bt59ActionPerformed

    private void bt60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt60ActionPerformed
        buttonList.set(60, bt60);
        buttonAction(60);       // TODO add your handling code here:
    }//GEN-LAST:event_bt60ActionPerformed

    private void bt61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt61ActionPerformed
        buttonList.set(61, bt61);
        buttonAction(61);        // TODO add your handling code here:
    }//GEN-LAST:event_bt61ActionPerformed

    private void bt62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt62ActionPerformed
        buttonList.set(62, bt62);
        buttonAction(62);        // TODO add your handling code here:
    }//GEN-LAST:event_bt62ActionPerformed

    private void bt63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt63ActionPerformed
        buttonList.set(63, bt63);
        buttonAction(63);        // TODO add your handling code here:
    }//GEN-LAST:event_bt63ActionPerformed

    private void bt64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt64ActionPerformed
        buttonList.set(64, bt64);
        buttonAction(64);        // TODO add your handling code here:
    }//GEN-LAST:event_bt64ActionPerformed

    private void bt65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt65ActionPerformed
        buttonList.set(65, bt65);
        buttonAction(65);        // TODO add your handling code here:
    }//GEN-LAST:event_bt65ActionPerformed

    private void bt66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt66ActionPerformed
        buttonList.set(66, bt66);
        buttonAction(66);       // TODO add your handling code here:
    }//GEN-LAST:event_bt66ActionPerformed

    private void bt67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt67ActionPerformed
        buttonList.set(67, bt67);
        buttonAction(67);       // TODO add your handling code here:
    }//GEN-LAST:event_bt67ActionPerformed

    private void bt68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt68ActionPerformed
        buttonList.set(68, bt68);
        buttonAction(68);       // TODO add your handling code here:
    }//GEN-LAST:event_bt68ActionPerformed

    private void bt69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt69ActionPerformed
        buttonList.set(69, bt69);
        buttonAction(69);        // TODO add your handling code here:
    }//GEN-LAST:event_bt69ActionPerformed

    private void bt70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt70ActionPerformed
        buttonList.set(70, bt70);
        buttonAction(70);        // TODO add your handling code here:
    }//GEN-LAST:event_bt70ActionPerformed

    private void bt71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt71ActionPerformed
        buttonList.set(71, bt71);
        buttonAction(71);        // TODO add your handling code here:
    }//GEN-LAST:event_bt71ActionPerformed

    private void bt72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt72ActionPerformed
        buttonList.set(72, bt72);
        buttonAction(72);       // TODO add your handling code here:
    }//GEN-LAST:event_bt72ActionPerformed

    private void bt73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt73ActionPerformed
        buttonList.set(73, bt73);
        buttonAction(73);       // TODO add your handling code here:
    }//GEN-LAST:event_bt73ActionPerformed

    private void bt74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt74ActionPerformed
        buttonList.set(74, bt74);
        buttonAction(74);       // TODO add your handling code here:
    }//GEN-LAST:event_bt74ActionPerformed

    private void bt75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt75ActionPerformed
        buttonList.set(75, bt75);
        buttonAction(75);        // TODO add your handling code here:
    }//GEN-LAST:event_bt75ActionPerformed

    private void bt76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt76ActionPerformed
        buttonList.set(76, bt76);
        buttonAction(76);       // TODO add your handling code here:
    }//GEN-LAST:event_bt76ActionPerformed

    private void bt77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt77ActionPerformed
        buttonList.set(77, bt77);
        buttonAction(77);       // TODO add your handling code here:
    }//GEN-LAST:event_bt77ActionPerformed

    private void bt78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt78ActionPerformed
        buttonList.set(78, bt78);
        buttonAction(78);       // TODO add your handling code here:
    }//GEN-LAST:event_bt78ActionPerformed

    private void bt79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt79ActionPerformed
        buttonList.set(79, bt79);
        buttonAction(79);       // TODO add your handling code here:
    }//GEN-LAST:event_bt79ActionPerformed

    private void bt80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt80ActionPerformed
        buttonList.set(80, bt80);
        buttonAction(80);        // TODO add your handling code here:
    }//GEN-LAST:event_bt80ActionPerformed

    private void bt81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt81ActionPerformed
        buttonList.set(81, bt81);
        buttonAction(81);        // TODO add your handling code here:
    }//GEN-LAST:event_bt81ActionPerformed

    private void bt82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt82ActionPerformed
        buttonList.set(82, bt82);
        buttonAction(82);        // TODO add your handling code here:
    }//GEN-LAST:event_bt82ActionPerformed

    private void bt83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt83ActionPerformed
        buttonList.set(83, bt83);
        buttonAction(83);        // TODO add your handling code here:
    }//GEN-LAST:event_bt83ActionPerformed

    private void bt84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt84ActionPerformed
        buttonList.set(84, bt84);
        buttonAction(84);       // TODO add your handling code here:
    }//GEN-LAST:event_bt84ActionPerformed

    private void bt85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt85ActionPerformed
        buttonList.set(85, bt85);
        buttonAction(85);        // TODO add your handling code here:
    }//GEN-LAST:event_bt85ActionPerformed

    private void bt86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt86ActionPerformed
        buttonList.set(86, bt86);
        buttonAction(86);       // TODO add your handling code here:
    }//GEN-LAST:event_bt86ActionPerformed

    private void bt87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt87ActionPerformed
        buttonList.set(87, bt87);
        buttonAction(87);        // TODO add your handling code here:
    }//GEN-LAST:event_bt87ActionPerformed

    private void bt88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt88ActionPerformed
        buttonList.set(88, bt88);
        buttonAction(88);        // TODO add your handling code here:
    }//GEN-LAST:event_bt88ActionPerformed

    private void bt89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt89ActionPerformed
        buttonList.set(89, bt89);
        buttonAction(89);        // TODO add your handling code here:
    }//GEN-LAST:event_bt89ActionPerformed

    private void bt90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt90ActionPerformed
        buttonList.set(90, bt90);
        buttonAction(90);        // TODO add your handling code here:
    }//GEN-LAST:event_bt90ActionPerformed

    private void bt91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt91ActionPerformed
        buttonList.set(91, bt91);
        buttonAction(91);       // TODO add your handling code here:
    }//GEN-LAST:event_bt91ActionPerformed

    private void bt92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt92ActionPerformed
        buttonList.set(92, bt92);
        buttonAction(92);        // TODO add your handling code here:
    }//GEN-LAST:event_bt92ActionPerformed

    private void bt93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt93ActionPerformed
        buttonList.set(93, bt93);
        buttonAction(93);        // TODO add your handling code here:
    }//GEN-LAST:event_bt93ActionPerformed

    private void bt94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt94ActionPerformed
        buttonList.set(94, bt94);
        buttonAction(94);       // TODO add your handling code here:
    }//GEN-LAST:event_bt94ActionPerformed

    private void bt95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt95ActionPerformed
        buttonList.set(95, bt95);
        buttonAction(95);        // TODO add your handling code here:
    }//GEN-LAST:event_bt95ActionPerformed

    private void bt96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt96ActionPerformed
        buttonList.set(96, bt96);
        buttonAction(96);        // TODO add your handling code here:
    }//GEN-LAST:event_bt96ActionPerformed

    private void bt97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt97ActionPerformed
        buttonList.set(97, bt97);
        buttonAction(97);        // TODO add your handling code here:
    }//GEN-LAST:event_bt97ActionPerformed

    private void bt98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt98ActionPerformed
        buttonList.set(98, bt98);
        buttonAction(98);        // TODO add your handling code here:
    }//GEN-LAST:event_bt98ActionPerformed

    private void bt99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt99ActionPerformed
        buttonList.set(99, bt99);
        buttonAction(99);        // TODO add your handling code here:
    }//GEN-LAST:event_bt99ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        timer.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton82ActionPerformed
    public void buttonAction(int i) {
        final Grid middleButton;
        middleButton = (Grid) (buttonList.get(i));
        if ((middleButton.ball) != null) {
            tempBall = middleButton.ball;
            movingGrid = middleButton;
        } else if ((middleButton.ball) == null) {

            if (tempBall == null) {
                middleButton.setBackground(null);
            } else {
                middleButton.CreateTheBall(tempBall.color);
                middleButton.setBackground((middleButton.ball).color);
                movingGrid.ball=null;
                movingGrid.setBackground(null);
                tempBall = null;
                createThreeBall();
            }
        } // TODO add your handling code here:
    }

    public int findThePosition() {
        Grid tempGrid = null;
        int result = 0;
        do {
            if (isGameOver()) {
                JOptionPane.showMessageDialog(null, "Sorry~ 游戏结束咯~");
                System.exit(0);
            }
            int a = (int) (Math.random() * 10);
            int b = (int) (Math.random() * 10);
            Point tempPoint = new Point(a, b);
            for (int i = 0; i <= 99; i++) {
                if (((Grid) buttonList.get(i)).coodrinate.equals(tempPoint)) {
                    tempGrid = (Grid) buttonList.get(i);
                    result = i;
                    break;
                }
            }
        } while (tempGrid.ball != null);
        return result;
    }

    public boolean isGameOver() {
        for (int i = 0; i <= 99; i++) {
            if (((Grid) buttonList.get(i)).ball == null) {
                return false;
            }
        }
        return true;
    }
    public void createThreeBall(){
        int temp1 = findThePosition();
        ((Grid) buttonList.get(temp1)).CreateTheBall();
        ((Grid) buttonList.get(temp1)).setBackground(((Grid) buttonList.get(temp1)).ball.color);
        int temp2 = findThePosition();
        ((Grid) buttonList.get(temp2)).CreateTheBall();
        ((Grid) buttonList.get(temp2)).setBackground(((Grid) buttonList.get(temp2)).ball.color);
        int temp3 = findThePosition();
        ((Grid) buttonList.get(temp3)).CreateTheBall();
        ((Grid) buttonList.get(temp3)).setBackground(((Grid) buttonList.get(temp3)).ball.color);
    }
    public int[] massArray() {
        int[] array = new int[100];
        for (int i = 0; i <= 99; i++) {
            array[i] = i;
        }
        for (int i = 0; i < 200; i++) {
            int a = (int) (Math.random() * 100);
            int b = (int) (Math.random() * 100);
            int temp;
            temp = array[a];
            array[a] = array[b];
            array[b] = temp;
        }
        return array;
    }//返回乱序数组
    /**
     * @param args the command line arguments
     */
    Timer timer = new Timer(500, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (flag) {
                bt0.setBackground((((Grid) bt0).ball).color);
                flag = false;
            } else {
                bt0.setBackground(null);
                flag = true;
            }
        }
    });
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt17;
    private javax.swing.JButton bt18;
    private javax.swing.JButton bt19;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton bt23;
    private javax.swing.JButton bt24;
    private javax.swing.JButton bt25;
    private javax.swing.JButton bt26;
    private javax.swing.JButton bt27;
    private javax.swing.JButton bt28;
    private javax.swing.JButton bt29;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt30;
    private javax.swing.JButton bt31;
    private javax.swing.JButton bt32;
    private javax.swing.JButton bt33;
    private javax.swing.JButton bt34;
    private javax.swing.JButton bt35;
    private javax.swing.JButton bt36;
    private javax.swing.JButton bt37;
    private javax.swing.JButton bt38;
    private javax.swing.JButton bt39;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt40;
    private javax.swing.JButton bt41;
    private javax.swing.JButton bt42;
    private javax.swing.JButton bt43;
    private javax.swing.JButton bt44;
    private javax.swing.JButton bt45;
    private javax.swing.JButton bt46;
    private javax.swing.JButton bt47;
    private javax.swing.JButton bt48;
    private javax.swing.JButton bt49;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt50;
    private javax.swing.JButton bt51;
    private javax.swing.JButton bt52;
    private javax.swing.JButton bt53;
    private javax.swing.JButton bt54;
    private javax.swing.JButton bt55;
    private javax.swing.JButton bt56;
    private javax.swing.JButton bt57;
    private javax.swing.JButton bt58;
    private javax.swing.JButton bt59;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt60;
    private javax.swing.JButton bt61;
    private javax.swing.JButton bt62;
    private javax.swing.JButton bt63;
    private javax.swing.JButton bt64;
    private javax.swing.JButton bt65;
    private javax.swing.JButton bt66;
    private javax.swing.JButton bt67;
    private javax.swing.JButton bt68;
    private javax.swing.JButton bt69;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt70;
    private javax.swing.JButton bt71;
    private javax.swing.JButton bt72;
    private javax.swing.JButton bt73;
    private javax.swing.JButton bt74;
    private javax.swing.JButton bt75;
    private javax.swing.JButton bt76;
    private javax.swing.JButton bt77;
    private javax.swing.JButton bt78;
    private javax.swing.JButton bt79;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt80;
    private javax.swing.JButton bt81;
    private javax.swing.JButton bt82;
    private javax.swing.JButton bt83;
    private javax.swing.JButton bt84;
    private javax.swing.JButton bt85;
    private javax.swing.JButton bt86;
    private javax.swing.JButton bt87;
    private javax.swing.JButton bt88;
    private javax.swing.JButton bt89;
    private javax.swing.JButton bt9;
    private javax.swing.JButton bt90;
    private javax.swing.JButton bt91;
    private javax.swing.JButton bt92;
    private javax.swing.JButton bt93;
    private javax.swing.JButton bt94;
    private javax.swing.JButton bt95;
    private javax.swing.JButton bt96;
    private javax.swing.JButton bt97;
    private javax.swing.JButton bt98;
    private javax.swing.JButton bt99;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
